# Generated by Django 6.1.1 on 2026-09-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('row_number', models.IntegerField()),
                ('field', models.CharField(max_length=50)),
                ('raw_value', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=100)),
                ('location_id', models.CharField(db_index=True, max_length=100)),
                ('raw_value', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('raw_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ref', models.CharField(max_length=100)),
                ('normalized_record_ref', models.CharField(db_index=True, max_length=100)),
                ('location_id', models.CharField(db_index=True, max_length=100)),
                ('raw_value', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('raw_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='reconciliation.organization')),
            ],
        ),
    ]
